apiVersion: v1
kind: Pod
metadata:
  name: chat
  labels:
    app.kubernetes.io/name: chat
spec:
  containers:
    - image: michwoj01/ecsb:chat
      name: chat
      ports:
        - containerPort: 2138
      resources: {}
  restartPolicy: OnFailure
status: {}
