apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    app.kubernetes.io/name: webapp
status:
  loadBalancer: {}
