apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
  strategy: {}
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: webapp
    spec:
      containers:
        - image: webapp
          imagePullPolicy: Never
          name: webapp
          ports:
            - containerPort: 5173
          resources: {}
      restartPolicy: Always
status: {}
