version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: on-failure
    env_file:
      - 'docker.env'
    environment:
      PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres15_data:/var/lib/postgresql/data
      - ./dbscripts/:/docker-entrypoint-initdb.d/
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - '15672:15672'
      - '5672:5672'
  redis:
    container_name: redis
    image: redis/redis-stack
    restart: on-failure
    ports:
      - '8001:8001'
      - '6379:6379'
    volumes:
      - ./cache:/redis_data
