apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
status:
  loadBalancer: {}
